name: Unit Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    secrets:
      app_id:
        required: true
      ssh_key:
        required: true

env:
  BUILD_TYPE: Release

jobs:
  unit_test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10

    steps:
    - name: Create token
      uses: actions/create-github-app-token@v1
      id: app_token
      with:
        app-id: ${{ secrets.app_id }}
        private-key: ${{ secrets.ssh_key }}
        owner: ${{ github.repository_owner }}

    - name: Clone Main Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ steps.app_token.outputs.token }}
        persist-credentials: false

    - name: Create Build Environment
      shell: bash
      run: |
        sudo apt-get install -y libgflags-dev libpmemobj-dev libnuma-dev
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ${GITHUB_WORKSPACE}
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
        -DPMWCAS_BENCH_BUILD_TESTS=ON

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel --config ${BUILD_TYPE}

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${BUILD_TYPE} --output-on-failure
